import { z } from "zod";

// IDs are client-generated (crypto.randomUUID), but legacy rows may predate
// that, so accept any short opaque string rather than strict UUIDs.
const idString = z.string().min(1).max(64);

// ============= AUTH =============
export const registerSchema = z.object({
  email: z.string().trim().toLowerCase().email("Invalid email address").max(255),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters")
    .max(128, "Password must be at most 128 characters"),
});

export const loginSchema = z.object({
  email: z.string().trim().toLowerCase().min(1, "Email and password are required").max(255),
  password: z.string().min(1, "Email and password are required").max(1024),
});

export const forgotPasswordSchema = z.object({
  email: z.string().trim().toLowerCase().min(1, "Email is required").max(255),
});

export const resetPasswordSchema = z.object({
  token: z.string().min(1, "Token and password are required").max(128),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters")
    .max(128, "Password must be at most 128 characters"),
});

// ============= DATA (highest-risk payloads) =============
export const transactionSchema = z.object({
  id: idString,
  budgetId: idString,
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date"),
  payee: z.string().max(500),
  categoryId: idString.nullish(),
  accountId: idString,
  amount: z.number().finite(),
  memo: z.string().max(2000).nullish(),
  cleared: z.boolean().default(false),
  autoGeneratedById: idString.nullish(),
});

const accountBalanceUpdateSchema = z.object({
  id: idString,
  balance: z.number().finite(),
  isActive: z.boolean().optional(),
});

export const createTransactionBodySchema = z.object({
  transaction: transactionSchema,
  accountUpdate: accountBalanceUpdateSchema.nullish(),
});

const monthKey = z.string().regex(/^\d{4}-\d{2}$/, "Invalid month key");

export const upsertAssignmentSchema = z.object({
  budgetId: idString,
  monthKey,
  categoryId: idString,
  amount: z.number().finite(),
});

export const bulkAssignmentsSchema = z.object({
  budgetId: idString,
  assignments: z
    .array(z.object({ monthKey, categoryId: idString, amount: z.number().finite() }))
    .max(1000),
});

/** safeParse wrapper returning the first issue message for a 400 response. */
export function parseBody<Schema extends z.ZodTypeAny>(
  schema: Schema,
  body: unknown,
): { data: z.infer<Schema>; error?: undefined } | { data?: undefined; error: string } {
  const result = schema.safeParse(body);
  if (!result.success) {
    return { error: result.error.issues[0]?.message ?? "Invalid request" };
  }
  return { data: result.data };
}
